//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceProjectClient.IzingaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProject")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfdelingValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AfmeldtValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlarmValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoligValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaleValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TidValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AfdelingValue {
            get {
                return this.AfdelingValueField;
            }
            set {
                if ((object.ReferenceEquals(this.AfdelingValueField, value) != true)) {
                    this.AfdelingValueField = value;
                    this.RaisePropertyChanged("AfdelingValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AfmeldtValue {
            get {
                return this.AfmeldtValueField;
            }
            set {
                if ((this.AfmeldtValueField.Equals(value) != true)) {
                    this.AfmeldtValueField = value;
                    this.RaisePropertyChanged("AfmeldtValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlarmValue {
            get {
                return this.AlarmValueField;
            }
            set {
                if ((object.ReferenceEquals(this.AlarmValueField, value) != true)) {
                    this.AlarmValueField = value;
                    this.RaisePropertyChanged("AlarmValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoligValue {
            get {
                return this.BoligValueField;
            }
            set {
                if ((object.ReferenceEquals(this.BoligValueField, value) != true)) {
                    this.BoligValueField = value;
                    this.RaisePropertyChanged("BoligValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDValue {
            get {
                return this.IDValueField;
            }
            set {
                if ((this.IDValueField.Equals(value) != true)) {
                    this.IDValueField = value;
                    this.RaisePropertyChanged("IDValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NavnValue {
            get {
                return this.NavnValueField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnValueField, value) != true)) {
                    this.NavnValueField = value;
                    this.RaisePropertyChanged("NavnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonaleValue {
            get {
                return this.PersonaleValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaleValueField, value) != true)) {
                    this.PersonaleValueField = value;
                    this.RaisePropertyChanged("PersonaleValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TidValue {
            get {
                return this.TidValueField;
            }
            set {
                if ((this.TidValueField.Equals(value) != true)) {
                    this.TidValueField = value;
                    this.RaisePropertyChanged("TidValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IzingaService.IIzingaService")]
    public interface IIzingaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIzingaService/GetLogs", ReplyAction="http://tempuri.org/IIzingaService/GetLogsResponse")]
        WebServiceProjectClient.IzingaService.Log[] GetLogs(string parameter1, string parameter2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIzingaService/GetLogs", ReplyAction="http://tempuri.org/IIzingaService/GetLogsResponse")]
        System.Threading.Tasks.Task<WebServiceProjectClient.IzingaService.Log[]> GetLogsAsync(string parameter1, string parameter2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIzingaServiceChannel : WebServiceProjectClient.IzingaService.IIzingaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IzingaServiceClient : System.ServiceModel.ClientBase<WebServiceProjectClient.IzingaService.IIzingaService>, WebServiceProjectClient.IzingaService.IIzingaService {
        
        public IzingaServiceClient() {
        }
        
        public IzingaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IzingaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IzingaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IzingaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServiceProjectClient.IzingaService.Log[] GetLogs(string parameter1, string parameter2) {
            return base.Channel.GetLogs(parameter1, parameter2);
        }
        
        public System.Threading.Tasks.Task<WebServiceProjectClient.IzingaService.Log[]> GetLogsAsync(string parameter1, string parameter2) {
            return base.Channel.GetLogsAsync(parameter1, parameter2);
        }
    }
}
